languages:
- adjectives: []
  adjs:
  name: German
  nouns:
  - masc: []
  - fem: []
  - neut:
  preps: []
  verbs: []
- adjectives: []
  name: Polish
  nouns:
  prepositions: []
  verbs:
- name: Spanish
  nouns: []
