languages:
  Spanish:
    adjs: []
    nouns-f: []
    nouns-m: []
    preps: []
    verbs: [hablar]
    verbs-conditional-1ppl: {hablar: "hablar\xEDamos"}
    verbs-conditional-1psing: {hablar: "hablar\xEDa"}
    verbs-conditional-2pfam: {hablar: "hablar\xEDas"}
    verbs-conditional-2pfampl: {hablar: "hablar\xEDan"}
    verbs-conditional-2ppol: {hablar: "hablar\xEDa"}
    verbs-conditional-2ppolpl: {hablar: "hablar\xEDan"}
    verbs-conditional-3ppl: {hablar: "hablar\xEDan"}
    verbs-conditional-3psing: {hablar: "hablar\xEDa"}
    verbs-en-inf: {hablar: speak}
    verbs-en-simple-past: {hablar: spoke}
    verbs-future-1ppl: {hablar: hablaremos}
    verbs-future-1psing: {hablar: "hablar\xE9"}
    verbs-future-2pfam: {hablar: "hablar\xE1s"}
    verbs-future-2pfampl: {hablar: "hablar\xE1n"}
    verbs-future-2ppol: {hablar: "hablar\xE1"}
    verbs-future-2ppolpl: {hablar: "hablar\xE1n"}
    verbs-future-3ppl: {hablar: "hablar\xE1n"}
    verbs-future-3psing: {hablar: "hablar\xE1"}
    verbs-imperfect-past-1ppl: {hablar: hablabamos}
    verbs-imperfect-past-1psing: {hablar: hablaba}
    verbs-imperfect-past-2pfam: {hablar: hablabas}
    verbs-imperfect-past-2pfampl: {hablar: hablaban}
    verbs-imperfect-past-2ppol: {hablar: hablaba}
    verbs-imperfect-past-2ppolpl: {hablar: hablaban}
    verbs-imperfect-past-3ppl: {hablar: hablaban}
    verbs-imperfect-past-3psing: {hablar: hablaba}
    verbs-present-1ppl: {hablar: hablamos}
    verbs-present-1psing: {hablar: hablo}
    verbs-present-2pfam: {hablar: hablas}
    verbs-present-2pfampl: {hablar: hablan}
    verbs-present-2ppol: {hablar: habla}
    verbs-present-2ppolpl: {hablar: hablan}
    verbs-present-3ppl: {hablar: hablan}
    verbs-present-3psing: {hablar: habla}
    verbs-present-cont-1ppl: {hablar: estamos hablando}
    verbs-present-cont-1psing: {hablar: estoy hablando}
    verbs-present-cont-2pfam: {hablar: estas hablando}
    verbs-present-cont-2pfampl: {hablar: estan hablando}
    verbs-present-cont-2ppol: {hablar: esta hablando}
    verbs-present-cont-2ppolpl: {hablar: estan hablando}
    verbs-present-cont-3ppl: {hablar: estan hablando}
    verbs-present-cont-3psing: {hablar: esta hablando}
    verbs-present-perf-1ppl: {hablar: hemos hablado}
    verbs-present-perf-1psing: {hablar: he hablado}
    verbs-present-perf-2pfam: {hablar: has hablado}
    verbs-present-perf-2pfampl: {hablar: han hablado}
    verbs-present-perf-2ppol: {hablar: ha hablado}
    verbs-present-perf-2ppolpl: {hablar: han hablado}
    verbs-present-perf-3ppl: {hablar: han hablado}
    verbs-present-perf-3psing: {hablar: ha hablado}
    verbs-simple-past-1ppl: {hablar: hablamos}
    verbs-simple-past-1psing: {hablar: "habl\xE9"}
    verbs-simple-past-2pfam: {hablar: hablaste}
    verbs-simple-past-2pfampl: {hablar: hablaron}
    verbs-simple-past-2ppol: {hablar: "habl\xF3"}
    verbs-simple-past-2ppolpl: {hablar: hablaron}
    verbs-simple-past-3ppl: {hablar: hablaron}
    verbs-simple-past-3psing: {hablar: "habl\xF3"}
